### ISSUE TITLE
User can create a container

### ISSUE THREAD

**Issue by lauragracem** [lauragracem/final-project#1]
## ⚙️ Feature

User can select the type of container they want to work with.

## 📐 Functionality

User will see four types of containers they can choose from. Each type of container will have 2 - 3 subtypes the user will choose from. 

## 🖼️ Wireframes

![User can create a container](https://user-images.githubusercontent.com/60913524/184444746-7c09d3b5-6a55-40ef-b9d3-a97c1faeffd8.png)
![User can customize container 1](https://user-images.githubusercontent.com/60913524/181649058-680f9273-4a0e-4507-9b5c-cac7672ec71e.png)
![User can customize container 2](https://user-images.githubusercontent.com/60913524/181649059-d50fd19f-550b-4cfa-a010-56cff4edfe6b.png)
![User can customize container 3](https://user-images.githubusercontent.com/60913524/181649060-5367a596-6b03-4235-9761-94429587e2d1.png)
![User can customize container 4](https://user-images.githubusercontent.com/60913524/181649061-26d7ba97-3fd2-4659-ad9f-d43fa335dbb2.png)

![User can create a container](https://user-images.githubusercontent.com/60913524/184445317-e8932a72-5325-4b23-a3b5-96e181403596.png)
![User can customize container 1](https://user-images.githubusercontent.com/60913524/181648844-73eefe57-4317-46a0-afe7-beebc09d4584.png)
![User can customize container 2](https://user-images.githubusercontent.com/60913524/181648845-3ca806c4-2a48-4147-bbe1-075b070dcb8b.png)
![User can customize container 3](https://user-images.githubusercontent.com/60913524/181648848-5174c425-3212-4ade-bb8b-6ec691c6db61.png)
![User can customize container 4](https://user-images.githubusercontent.com/60913524/181648849-ff47cc23-5593-4bbf-bec5-4d421b264a25.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create components for different container options.
   - [x] Create box component for home page.
   - [x] Create jar component for home page.
   - [x] Create basket component for home page.
   - [x] Create backpack component for home page.
- [x] Update components' bootstrap support classes.
- [x] Create pages for different containers.
   - [x] Create a page that will contain the box components.
   - [x] Create a page that will contain the jar components.
   - [x] Create a page that will contain the basket components.
   - [x] Create a page that will contain the backpack components. 
- [x] Create a home page.
- [x] Create a page for uploading user containers.
- [x] Create a page for uploading user images.
- [x] Create a page for uploading user items.
- [x] Utilize hashrouter to navigate from home page to container pages. 
- [ ] Add a back arrow button to return from container pages to home page. 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
